# Generated by Django 3.2.13 on 2022-06-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20220629_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_datetime']},
        ),
    ]
