# Generated by Django 3.2.13 on 2022-06-30 11:02

from django.db import migrations, models
import flight.models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.CharField(max_length=2, validators=[flight.models.check_airport]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(max_length=2, validators=[flight.models.check_airport]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(validators=[flight.models.check_departure_time]),
        ),
    ]
