# Generated by Django 3.2.13 on 2022-06-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_alter_aircraft_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={},
        ),
    ]
